title: ShardaLearningCenter
email: s.learnkarma@gmail.com
description: >- 
  Learn to code by building real projects. Fast. Practical. No fluff.
baseurl: "" 
url: "shaardalearningcenter.github.io" 
theme: minima
plugins:
  - jekyll-feed
